-- Insert data into the university table
INSERT INTO university (name)
VALUES ('OLYMPUS Szkoła Wyższa im. Romualda Kudlińskiego (61)'),
       ('ALMAMER Wyższa Szkoła Ekonomiczna (42)'),
       ('Akademia Ekonomiczna im. Karola Adamieckiego w Katowicach'),
       ('Akademia Finansów (2)'),
       ('Akademia Górniczo-Hutnicza im. Stanisława Staszica w Krakowie'),
       ('Akademia Leona Koźmińskiego (16)'),
       ('Akademia Marynarki Wojennej im. Bohaterów Westerplatte (Gdynia)'),
       ('Akademia Medyczna im. Piastów Śląskich we Wrocławiu'),
       ('Akademia Morska w Gdyni'),
       ('Akademia Morska w Szczecinie'),
       ('Akademia Muzyczna im. Feliksa Nowowiejskiego w Bydgoszczy'),
       ('Akademia Muzyczna im. Grażyny i Kiejstuta Bacewiczów w Łodzi'),
       ('Akademia Muzyczna im. Ignacego Jana Paderewskiego w Poznaniu'),
       ('Akademia Muzyczna im. Karola Lipińskiego we Wrocławiu'),
       ('Akademia Muzyczna im. Karola Szymanowskiego w Katowicach'),
       ('Akademia Muzyczna im. Stanisława Moniuszki w Gdańsku'),
       ('Akademia Muzyczna w Krakowie'),
       ('Akademia Obrony Narodowej (Warszawa)'),
       ('Akademia Pedagogiki Specjalnej im. Marii Grzegorzewskiej (Warszawa)'),
       ('Akademia Podlaska w Siedlcach'),
       ('Akademia Pomorska w Słupsku'),
       ('Akademia Sztuk Pięknych im. Eugeniusza Gepperta we Wrocławiu'),
       ('Akademia Sztuk Pięknych im. Jana Matejki w Krakowie'),
       ('Akademia Sztuk Pięknych im. Władysława Strzemińskiego w Łodzi'),
       ('Akademia Sztuk Pięknych w Gdańsku'),
       ('Akademia Sztuk Pięknych w Katowicach'),
       ('Akademia Sztuk Pięknych w Poznaniu'),
       ('Akademia Sztuk Pięknych w Warszawie'),
       ('Akademia Teatralna im. Aleksandra Zelwerowicza w Warszawie'),
       ('Akademia Techniczno-Humanistyczna w Bielsku-Białej'),
       ('Akademia Wychowania Fizycznego Józefa Piłsudskiego w Warszawie'),
       ('Akademia Wychowania Fizycznego i Sportu im. Jędrzeja Śniadeckiego w Gdańsku'),
       ('Akademia Wychowania Fizycznego im. Bronisława Czecha w Krakowie'),
       ('Akademia Wychowania Fizycznego im. Eugeniusza Piaseckiego w Poznaniu'),
       ('Akademia Wychowania Fizycznego im. Jerzego Kukuczki w Katowicach'),
       ('Akademia Wychowania Fizycznego we Wrocławiu'),
       ('Akademia im. Jana Długosza w Częstochowie'),
       ('Bielska Wyższa Szkoła im. Józefa Tyszkiewicza (94)'),
       ('Chrześcijańska Akademia Teologiczna w Warszawie'),
       ('Collegium Civitas (127)'),
       ('Collegium Varsoviense (140)'),
       ('Dolnośląska Szkoła Wyższa (118)'),
       ('Dolnośląska Wyższa Szkoła Służb Publicznych "Asesor" (44 wsz)'),
       ('Europejska Akademia Sztuk (7)'),
       ('Europejska Wyższa Szkoła Biznesu w likwidacji (41 wsz)'),
       ('Europejska Wyższa Szkoła Informatyczno-Ekonomiczna (189 wsz)'),
       ('Europejska Wyższa Szkoła Prawa i Administracji (137)'),
       ('Ewangelikalna Wyższa Szkoła Teologiczna (186 wsz)'),
       ('Gdański Uniwersytet Medyczny'),
       ('Instytut Teologiczny im. bł. Wincentego Kadłubka w Sandomierzu'),
       ('Instytut Teologiczny im. św. Jana Kantego w Bielsku-Białej'),
       ('Kaszubsko-Pomorska Szkoła Wyższa (137 wsz)'),
       ('Katolicki Uniwersytet Lubelski Jana Pawła II'),
       ('Kolegium Karkonoskie w Jeleniej Górze'),
       ('Lingwistyczna Szkoła Wyższa (29 wsz)'),
       ('Małopolska Wyższa Szkoła Ekonomiczna (64)'),
       ('Międzynarodowa Wyższa Szkoła Logistyki i Transportu (67 wsz)'),
       ('Niepaństwowa Wyższa Szkoła Pedagogiczna (83)1)'),
       ('Niepubliczna Wyższa Szkoła Kosmetyczna (185 wsz)'),
       ('Papieski Wydział Teologiczny w Warszawie'),
       ('Papieski Wydział Teologiczny we Wrocławiu'),
       ('Państwowa Medyczna Wyższa Szkoła Zawodowa w Opolu'),
       ('Państwowa Wyższa Szkoła Filmowa, Telewizyjna i Teatralna im. Leona Schillera w Łodzi'),
       ('Państwowa Wyższa Szkoła Informatyki i Przedsiębiorczości w Łomży'),
       ('Państwowa Wyższa Szkoła Teatralna im. Leona Solskiego w Krakowie'),
       ('Państwowa Wyższa Szkoła Wschodnioeuropejska w Przemyślu'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Angelusa Silesiusa w Wałbrzychu'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Jana Amosa Komeńskiego w Lesznie'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Jana Gródka w Sanoku'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Papieża Jana Pawła II w Białej Podlaskiej'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Prezydenta Stanisława Wojciechowskiego w Kaliszu'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Stanisława Staszica w Pile'),
       ('Państwowa Wyższa Szkoła Zawodowa im. Witelona w Legnicy'),
       ('Państwowa Wyższa Szkoła Zawodowa im. ks. Bronisława Markiewicza w Jarosławiu'),
       ('Państwowa Wyższa Szkoła Zawodowa im. prof. Stanisława Tarnowskiego w Tarnobrzegu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Chełmie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Ciechanowie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Elblągu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Gnieźnie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Gorzowie Wielkopolskim'),
       ('Państwowa Wyższa Szkoła Zawodowa w Głogowie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Koninie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Krośnie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Nowym Sączu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Nysie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Oświęcimiu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Płocku'),
       ('Państwowa Wyższa Szkoła Zawodowa w Raciborzu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Sandomierzu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Skierniewicach'),
       ('Państwowa Wyższa Szkoła Zawodowa w Sulechowie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Suwałkach'),
       ('Państwowa Wyższa Szkoła Zawodowa w Tarnowie'),
       ('Państwowa Wyższa Szkoła Zawodowa w Wałczu'),
       ('Państwowa Wyższa Szkoła Zawodowa w Zamościu'),
       ('Państwowa Wyższa Szkoła Zawodowa we Włocławku'),
       ('Pedagogium - Wyższa Szkoła Pedagogiki Resocjalizacyjnej (150 wsz)'),
       ('Podhalańska Państwowa Wyższa Szkoła Zawodowa w Nowym Targu'),
       ('Politechnika Białostocka'),
       ('Politechnika Częstochowska'),
       ('Politechnika Gdańska'),
       ('Politechnika Koszalińska'),
       ('Politechnika Krakowska im. Tadeusza Kościuszki'),
       ('Politechnika Lubelska'),
       ('Politechnika Opolska'),
       ('Politechnika Poznańska'),
       ('Politechnika Radomska im. Kazimierza Pułaskiego'),
       ('Politechnika Rzeszowska im. Ignacego Łukasiewicza'),
       ('Politechnika Warszawska'),
       ('Politechnika Wrocławska'),
       ('Politechnika Łódzka'),
       ('Politechnika Śląska (Gliwice)'),
       ('Politechnika Świętokrzyska w Kielcach'),
       ('Polsko-Japońska Wyższa Szkoła Technik Komputerowych (51)'),
       ('Pomorska Akademia Medyczna w Szczecinie'),
       ('Prawosławne Seminarium Duchowne w Warszawie'),
       ('Prywatna Wyższa Szkoła Businessu, Administracji i Technik Komputerowych (1)'),
       ('Szczecińska Szkoła Wyższa Collegium Balticum (37 wsz)'),
       ('Szkoła Główna Gospodarstwa Wiejskiego w Warszawie'),
       ('Szkoła Główna Handlowa w Warszawie'),
       ('Szkoła Główna Służby Pożarniczej (Warszawa)'),
       ('Szkoła Wyższa Przymierza Rodzin (69 wsz)'),
       ('Szkoła Wyższa Psychologii Społecznej (95)'),
       ('Szkoła Wyższa Rzemiosł Artystycznych i Zarządzania (114 wsz)'),
       ('Szkoła Wyższa Rzemiosł Artystycznych w likwidacji (90 wsz)'),
       ('Szkoła Wyższa im. Bogdana Jańskiego (28)'),
       ('Toruńska Szkoła Wyższa (138 wsz)'),
       ('Toruńska Wyższa Szkoła Przedsiębiorczości (203 wsz)'),
       ('Uczelnia Warszawska im. Marii Skłodowskiej-Curie (106)'),
       ('Uniwersytet Ekonomiczny w Krakowie'),
       ('Uniwersytet Ekonomiczny w Poznaniu'),
       ('Uniwersytet Ekonomiczny we Wrocławiu'),
       ('Uniwersytet Gdański'),
       ('Uniwersytet Humanistyczno-Przyrodniczy Jana Kochanowskiego w Kielcach'),
       ('Uniwersytet Jagielloński w Krakowie'),
       ('Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie'),
       ('Uniwersytet Kazimierza Wielkiego w Bydgoszczy'),
       ('Uniwersytet Marii Curie-Skłodowskiej w Lublinie'),
       ('Uniwersytet Medyczny im. Karola Marcinkowskiego w Poznaniu'),
       ('Uniwersytet Medyczny w Białymstoku'),
       ('Uniwersytet Medyczny w Lublinie'),
       ('Uniwersytet Medyczny w Łodzi'),
       ('Uniwersytet Mikołaja Kopernika w Toruniu'),
       ('Uniwersytet Muzyczny Fryderyka Chopina (Warszawa)'),
       ('Uniwersytet Opolski'),
       ('Uniwersytet Papieski Jana Pawła II (Kraków)'),
       ('Uniwersytet Pedagogiczny im. Komisji Edukacji Narodowej w Krakowie'),
       ('Uniwersytet Przyrodniczy w Lublinie'),
       ('Uniwersytet Przyrodniczy w Poznaniu'),
       ('Uniwersytet Przyrodniczy we Wrocławiu'),
       ('Uniwersytet Rolniczy im. Hugona Kołłątaja w Krakowie'),
       ('Uniwersytet Rzeszowski'),
       ('Uniwersytet Szczeciński'),
       ('Uniwersytet Technologiczno-Przyrodniczy im. Jana i Jędrzeja Śniadeckich w Bydgoszczy'),
       ('Uniwersytet Warmińsko-Mazurski w Olsztynie'),
       ('Uniwersytet Warszawski'),
       ('Uniwersytet Wrocławski'),
       ('Uniwersytet Zielonogórski'),
       ('Uniwersytet im. Adama Mickiewicza w Poznaniu'),
       ('Uniwersytet w Białymstoku'),
       ('Uniwersytet Łódzki'),
       ('Uniwersytet Śląski w Katowicach'),
       ('Warszawska Szkoła Biznesu w likwidacji (24)'),
       ('Warszawska Szkoła Zarządzania - Szkoła Wyższa (12)'),
       ('Warszawska Wyższa Szkoła Ekonomiczna im. Edwarda Wiszniewskiego (35)'),
       ('Warszawska Wyższa Szkoła Humanistyczna im. Bolesława Prusa (105 wsz)'),
       ('Warszawska Wyższa Szkoła Informatyki (45 wsz)'),
       ('Warszawski Uniwersytet Medyczny'),
       ('Warszawskie Seminarium Teologiczne'),
       ('Wielkopolska Wyższa Szkoła Społeczno-Ekonomiczna (182 wsz)'),
       ('Wojskowa Akademia Techniczna im. Jarosława Dąbrowskiego (Warszawa)'),
       ('Wrocławska Wyższa Szkoła Informatyki Stosowanej (157 wsz)'),
       ('Wszechnica Polska - Szkoła Wyższa TWP (56 wsz)'),
       ('Wyższa Szkoła - Edukacja w Sporcie (111 wsz)'),
       ('Wyższa Szkoła Administracji (119)'),
       ('Wyższa Szkoła Administracji Publicznej (58)'),
       ('Wyższa Szkoła Administracji Publicznej im. Stanisława Staszica (102)'),
       ('Wyższa Szkoła Administracyjno-Społeczna (130 wsz)'),
       ('Wyższa Szkoła Artystyczna - WSA (201 wsz)'),
       ('Wyższa Szkoła Bankowa (7 wsz)'),
       ('Wyższa Szkoła Bankowa (8 wsz)'),
       ('Wyższa Szkoła Bankowości i Finansów (66)'),
       ('Wyższa Szkoła Bezpieczeństwa i Ochrony (171 wsz)'),
       ('Wyższa Szkoła Cła i Logistyki (54 wsz)'),
       ('Wyższa Szkoła Dziennikarska im. Melchiora Wańkowicza (71)'),
       ('Wyższa Szkoła Ekologii i Zarządzania (62)'),
       ('Wyższa Szkoła Ekonomiczna (47 wsz)'),
       ('Wyższa Szkoła Ekonomiczna (77)'),
       ('Wyższa Szkoła Ekonomiczno-Humanistyczna (126)'),
       ('Wyższa Szkoła Ekonomiczno-Informatyczna (93)'),
       ('Wyższa Szkoła Ekonomiczno-Turystyczna (71 wsz)'),
       ('Wyższa Szkoła Filologiczna (94 wsz)'),
       ('Wyższa Szkoła Filologii Hebrajskiej (205 wsz)'),
       ('Wyższa Szkoła Filozoficzno-Pedagogiczna "Ignatianum" w Krakowie'),
       ('Wyższa Szkoła Finansów i Zarządzania (143)'),
       ('Wyższa Szkoła Finansów i Zarządzania (23)'),
       ('Wyższa Szkoła Fizjoterapii (15 wsz)'),
       ('Wyższa Szkoła Gospodarowania Nieruchomościami (120)'),
       ('Wyższa Szkoła Handlowa (111)'),
       ('Wyższa Szkoła Handlu i Finansów Międzynarodowych im. Fryderyka Skarbka (70)'),
       ('Wyższa Szkoła Handlu i Prawa im. Ryszarda Łazarskiego (22)'),
       ('Wyższa Szkoła Hotelarstwa, Gastronomii i Turystyki (84)'),
       ('Wyższa Szkoła Humanistyczna (113 wsz)'),
       ('Wyższa Szkoła Humanistyczna TWP (114)'),
       ('Wyższa Szkoła Humanistyczno-Ekonomiczna (69)'),
       ('Wyższa Szkoła Humanistyczno-Ekonomiczna (79 wsz)'),
       ('Wyższa Szkoła Informatyki Stosowanej i Zarządzania (87)'),
       ('Wyższa Szkoła Informatyki i Zarządzania "COPERNICUS" (88 wsz)'),
       ('Wyższa Szkoła Informatyki i Zarządzania (98)'),
       ('Wyższa Szkoła Informatyki, Zarządzania i Administracji (146)'),
       ('Wyższa Szkoła Infrastruktury i Zarządzania (142 wsz)'),
       ('Wyższa Szkoła Integracji Europejskiej (26 wsz)'),
       ('Wyższa Szkoła Języków Obcych (162 wsz)'),
       ('Wyższa Szkoła Języków Obcych (87 wsz)'),
       ('Wyższa Szkoła Komunikowania i Mediów Społecznych im. Jerzego Giedroycia (39)'),
       ('Wyższa Szkoła Komunikowania, Politologii i Stosunków Międzynarodowych (169 wsz)'),
       ('Wyższa Szkoła Kosmetologii i Ochrony Zdrowia (123 wsz)'),
       ('Wyższa Szkoła Kosmetologii i Promocji Zdrowia (184 wsz)'),
       ('Wyższa Szkoła Kultury Społecznej i Medialnej (75 wsz)'),
       ('Wyższa Szkoła Liderów Społecznych i Mediów (183 wsz)'),
       ('Wyższa Szkoła Matematyki i Informatyki Użytkowej (79)'),
       ('Wyższa Szkoła Mazowiecka (160 wsz)'),
       ('Wyższa Szkoła Menedżerska (140 wsz)'),
       ('Wyższa Szkoła Menedżerska (147 wsz)'),
       ('Wyższa Szkoła Menedżerska (60)'),
       ('Wyższa Szkoła Oficerska Sił Powietrznych (Dęblin)'),
       ('Wyższa Szkoła Oficerska Wojsk Lądowych im. Generała Tadeusz Kościuszki we Wrocławiu'),
       ('Wyższa Szkoła Organizacji Turystyki i Hotelarstwa (95 wsz)'),
       ('Wyższa Szkoła Pedagogiczna TWP (20)'),
       ('Wyższa Szkoła Pedagogiczna ZNP (53)'),
       ('Wyższa Szkoła Policji (Szczytno)'),
       ('Wyższa Szkoła Promocji (61 wsz)'),
       ('Wyższa Szkoła Przedsiębiorczości (207 wsz)'),
       ('Wyższa Szkoła Rehabilitacji (188 wsz)'),
       ('Wyższa Szkoła Społeczno-Ekonomiczna (89)'),
       ('Wyższa Szkoła Stosunków Międzynarodowych i Amerykanistyki (123)'),
       ('Wyższa Szkoła Sztuk Wizualnych i Nowych Mediów w likwidacji (106 wsz)'),
       ('Wyższa Szkoła Sztuki Użytkowej (68)'),
       ('Wyższa Szkoła Techniczno-Ekonomiczna (101 wsz)'),
       ('Wyższa Szkoła Techniczno-Ekonomiczna (70 wsz)'),
       ('Wyższa Szkoła Techniki i Przedsiębiorczości (172 wsz)'),
       ('Wyższa Szkoła Technologii Informatycznych (164 wsz)'),
       ('Wyższa Szkoła Technologii Teleinformatycznych (81 wsz)'),
       ('Wyższa Szkoła Teologiczno-Humanistyczna im. Michała Beliny-Czechowskiego w Podkowie Leśnej'),
       ('Wyższa Szkoła Trenerów Sportu (206 wsz)'),
       ('Wyższa Szkoła Turystyki i Języków Obcych (141 wsz)'),
       ('Wyższa Szkoła Turystyki i Rekreacji im. Mieczysława Orłowicza (56)'),
       ('Wyższa Szkoła Współpracy Międzynarodowej i Regionalnej im. Zygmunta Glogera (174 wsz)'),
       ('Wyższa Szkoła Wychowania Fizycznego i Turystyki (72 wsz)'),
       ('Wyższa Szkoła Zarządzania "Edukacja" (122)'),
       ('Wyższa Szkoła Zarządzania (3)'),
       ('Wyższa Szkoła Zarządzania (30 wsz)'),
       ('Wyższa Szkoła Zarządzania Personelem (63 wsz)'),
       ('Wyższa Szkoła Zarządzania i Finansów (59)'),
       ('Wyższa Szkoła Zarządzania i Prawa im. Heleny Chodkowskiej (6)'),
       ('Wyższa Szkoła Zawodowa "OECONOMICUS" PTE (23 wsz)'),
       ('Wyższa Szkoła Zawodowa Kosmetyki i Pielęgnacji Zdrowia (42 wsz)'),
       ('Wyższe Baptystyczne Seminarium Teologiczne w Warszawie'),
       ('Wyższe Seminarium Duchowne Kościoła Polskokatolickiego w Warszawie'),
       ('Wyższe Seminarium Duchowne Kościoła Starokatolickiego Mariawitów w Płocku'),
       ('Wyższe Seminarium Teologiczne im. Jana Łaskiego w Warszawie'),
       ('Zachodniopomorska Szkoła Biznesu (15)'),
       ('Zachodniopomorski Uniwersytet Technologiczny w Szczecinie'),
       ('Śląski Uniwersytet Medyczny w Katowicach');


-- Insert data into the users table
INSERT INTO users (nickname, university_id, field_of_study)
VALUES ('admin_user', 1, 'Computer Science'),
       ('user1', 1, 'Physics'),
       ('user2', 14, 'Biology'),
       ('user3', 39, 'Mathematics'),
       ('user4', 85, 'Chemistry'),
       ('user5', 64, 'History'),
       ('user6', 19, 'Economics'),
       ('user7', 57, 'Psychology'),
       ('user8', 3, 'English'),
       ('user9', 99, 'Engineering'),
       ('user10', 46, 'Political Science');

-- Insert data into the roles table
INSERT INTO roles (name)
VALUES ('ADMIN'),
       ('USER');

-- Insert data into the user_security_info table
INSERT INTO user_security_info (user_id, email, password)
VALUES (1, 'admin@example.com', '$2a$12$wsFZqukbU9e4usv6YYE4OuBXHZbAs9ksmrZ9YJwq5uCI2c4GGrn3u'),
       (2, 'user1@example.com', '$2a$12$16Ai8pXO4ieWyQYw6iQWhuVin78flKB7RsI21p.vVNfvRB69vfHzu'),
       (3, 'user2@example.com', '$2a$12$16Ai8pXO4ieWyQYw6iQWhuVin78flKB7RsI21p.vVNfvRB69vfHzu'),
       (4, 'user3@example.com', '$2a$12$16Ai8pXO4ieWyQYw6iQWhuVin78flKB7RsI21p.vVNfvRB69vfHzu'),
       (5, 'user4@example.com', '$2a$12$16Ai8pXO4ieWyQYw6iQWhuVin78flKB7RsI21p.vVNfvRB69vfHzu'),
       (6, 'user5@example.com', '$2a$12$16Ai8pXO4ieWyQYw6iQWhuVin78flKB7RsI21p.vVNfvRB69vfHzu'),
       (7, 'user6@example.com', '$2a$12$afJ68QkG97cgMFUHMQE9P.xm9.Ec4JQ.JSJsCWzvI1WNg32DuCqMO'),
       (8, 'user7@example.com', '$2a$12$afJ68QkG97cgMFUHMQE9P.xm9.Ec4JQ.JSJsCWzvI1WNg32DuCqMO'),
       (9, 'user8@example.com', '$2a$12$afJ68QkG97cgMFUHMQE9P.xm9.Ec4JQ.JSJsCWzvI1WNg32DuCqMO'),
       (10, 'user9@example.com', '$2a$12$afJ68QkG97cgMFUHMQE9P.xm9.Ec4JQ.JSJsCWzvI1WNg32DuCqMO');

-- Insert data into the users_roles table
INSERT INTO security_users_roles (security_user_id, role_id)
VALUES (1, 1), -- admin_user is an ADMIN
       (2, 2),
       (3, 2),
       (4, 2),
       (5, 2),
       (6, 2),
       (7, 2),
       (8, 2),
       (9, 2),
       (10, 2);

-- Insert data into the picture table
INSERT INTO picture(id, name, type, data)
VALUES ('123e4567-e89b-12d3-a456-426614174001','JohnDoe', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/1.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174002','JaneSmith', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/f1.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174003','BobJohnson', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/2.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174004','AliceWilliams', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/f2.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174005','MichaelBrown', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/3.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174006','EmilyDavis', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/f2.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174007','ChristopherJones', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/4.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174008','JessicaMoore', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/f4.jpg')::bytea),
       ('123e4567-e89b-12d3-a456-426614174009','DanielWilson', 'jpg', pg_read_binary_file('/docker-entrypoint-initdb.d/pics/5.jpg')::bytea);


-- Insert data into the 'teacher' table
INSERT INTO teacher (name, surname, avg_score, picture_id, university_id, created_by, created_date, modified_date)
VALUES ('John', 'Doe', 0, '123e4567-e89b-12d3-a456-426614174001', 2, 2, '2023-01-01', '2023-01-01'),
       ('Jane', 'Smith', 0, '123e4567-e89b-12d3-a456-426614174002', 3, 3, '2023-01-02', '2023-01-02'),
       ('Bob', 'Johnson', 0, '123e4567-e89b-12d3-a456-426614174003', 4, 4, '2023-01-03', '2023-01-03'),
       ('Alice', 'Williams', 0, '123e4567-e89b-12d3-a456-426614174004', 5, 5, '2023-01-04', '2023-01-04'),
       ('Michael', 'Brown', 0, '123e4567-e89b-12d3-a456-426614174005', 6, 6, '2023-01-05', '2023-01-05'),
       ('Emily', 'Davis', 0, '123e4567-e89b-12d3-a456-426614174006', 7, 7, '2023-01-06', '2023-01-06'),
       ('Christopher', 'Jones', 0, '123e4567-e89b-12d3-a456-426614174007', 8, 8, '2023-01-07', '2023-01-07'),
       ('Jessica', 'Moore', 0, '123e4567-e89b-12d3-a456-426614174008', 9, 9, '2023-01-08', '2023-01-08'),
       ('Daniel', 'Wilson', 0, '123e4567-e89b-12d3-a456-426614174009', 10, 10, '2023-01-09', '2023-01-09');


-- Insert data into the 'review' table
INSERT INTO review (score, teacher_id, subject_name, user_id, review_text, created_date)
VALUES (5, 1, 'Math', 2, 'Excellent teacher!', '2023-01-05 10:00:00'),
       (4, 2, 'Physics', 3, 'Very knowledgeable', '2023-01-06 11:00:00'),
       (3, 3, 'Chemistry', 4, 'Needs improvement', '2023-01-07 12:00:00'),
       (4, 4, 'Biology', 5, 'Good teaching skills', '2023-01-08 13:00:00'),
       (3, 5, 'History', 6, 'Average teaching skills', '2023-01-10 14:00:00'),
       (5, 6, 'Computer Science', 7, 'Fantastic teacher!', '2023-01-11 15:00:00'),
       (4, 7, 'English', 8, 'Great communication', '2023-01-12 16:00:00'),
       (3, 8, 'Economics', 9, 'Could be more engaging', '2023-01-13 17:00:00'),
       (5, 9, 'Art', 10, 'Inspiring lectures', '2023-01-14 18:00:00'),
       (4, 1, 'Math', 6, 'Clear explanations', '2023-01-15 10:30:00'),
       (3, 1, 'Math', 7, 'Helpful but could improve', '2023-01-16 11:30:00'),
       (5, 1, 'Math', 8, 'Best teacher ever!', '2023-01-17 12:30:00'),
       (4, 2, 'Physics', 9, 'Interactive classes', '2023-01-18 13:30:00'),
       (5, 2, 'Physics', 10, 'Passionate about the subject', '2023-01-19 14:30:00'),
       (3, 2, 'Physics', 6, 'Needs more practical examples', '2023-01-20 15:30:00'),
       (4, 3, 'Chemistry', 7, 'Interesting experiments', '2023-01-21 16:30:00'),
       (2, 3, 'Chemistry', 8, 'Difficult to understand', '2023-01-22 17:30:00'),
       (5, 3, 'Chemistry', 9, 'Great at simplifying complex concepts', '2023-01-23 18:30:00');

INSERT INTO likes (review_id, user_id) VALUES
                                           (1, 2),
                                           (2, 3),
                                           (3, 4),
                                           (4, 5),
                                           (5, 6),
                                           (6, 7),
                                           (7, 8),
                                           (8, 9),
                                           (9, 10),
                                           (10, 11),
                                           (11, 2),
                                           (12, 3),
                                           (13, 4),
                                           (14, 5),
                                           (15, 6),
                                           (16, 7),
                                           (17, 8),
                                           (18, 9),
                                           (1, 10),
                                           (2, 11),
                                           (3, 2),
                                           (4, 3),
                                           (5, 4),
                                           (6, 5),
                                           (7, 6),
                                           (8, 7),
                                           (9, 8),
                                           (10, 9),
                                           (11, 10),
                                           (12, 11),
                                           (13, 2),
                                           (14, 3),
                                           (15, 4),
                                           (16, 5),
                                           (17, 6),
                                           (18, 7),
                                           (1, 8),
                                           (2, 9),
                                           (3, 10),
                                           (4, 11),
                                           (5, 2),
                                           (6, 3),
                                           (7, 4),
                                           (8, 5),
                                           (9, 6),
                                           (10, 7),
                                           (11, 8),
                                           (12, 9),
                                           (13, 10),
                                           (14, 11),
                                           (15, 2),
                                           (16, 3),
                                           (17, 4),
                                           (18, 5),
                                           (1, 6),
                                           (2, 7),
                                           (3, 8),
                                           (4, 9),
                                           (5, 10),
                                           (6, 11),
                                           (7, 2),
                                           (8, 3),
                                           (9, 4),
                                           (10, 5),
                                           (11, 6),
                                           (12, 7),
                                           (13, 8),
                                           (14, 9),
                                           (15, 10),
                                           (16, 11),
                                           (17, 2),
                                           (18, 3),
                                           (1, 3),
                                           (2, 4),
                                           (3, 5),
                                           (4, 6),
                                           (5, 7),
                                           (6, 8),
                                           (7, 9),
                                           (8, 10),
                                           (9, 11),
                                           (10, 2),
                                           (11, 3),
                                           (12, 4),
                                           (13, 5),
                                           (14, 6),
                                           (15, 7),
                                           (16, 8),
                                           (17, 9),
                                           (18, 10),
                                           (1, 11),
                                           (2, 2),
                                           (3, 3),
                                           (4, 4),
                                           (5, 5),
                                           (6, 6),
                                           (7, 7),
                                           (8, 8),
                                           (9, 9),
                                           (10, 10),
                                           (11, 11),
                                           (12, 2),
                                           (13, 3),
                                           (14, 4),
                                           (15, 5),
                                           (16, 6),
                                           (17, 7),
                                           (18, 8),
                                           (1, 9),
                                           (2, 10),
                                           (3, 11);